#!/bin/bash

sui() {
  if [[ $# -eq 0 ]] ; then
      echo 'Provide executable for sui'
      return 1
  fi

  declare app=$( which "$1" )
  if [ $? -ne 0 ]; then
    echo "Unable to find $1 through which, passing direct"
    app=$1
  fi

  echo "水 $app"
  chmod +s $app
}

for comm in "$@"; do
  sui $comm
done

